### ISSUE TITLE
Alerts Does not have correct allowed types

### ISSUE THREAD

**Issue by alacercogitatus** [carbonblack/carbon-black-cloud-sdk-python#117]
https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/afc6840ef52799c5cdc63c4d654b43c45b7c0b40/src/cbc_sdk/platform/alerts.py#L317

"DEVICE_CONTROL" (https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/alerts-api/) is not listed, and this will fail. Please update! Thanks!

**Comment by abowersox-cb** [comment]
Pull Request #119 will close this issue, among other things.

**Comment by avanbrunt-cb** [comment]
Fixed in v1.1.1 release
