### ISSUE TITLE
[BUG] - Error in example code when setting fields for an Enriched Event Query 

### ISSUE THREAD

**Issue by tlansec** [carbonblack/carbon-black-cloud-sdk-python#143]
**I am seeing this behaviour on: **
 - OS: Windows 10 x64
 - Carbon Black Cloud Products: Endpoint standard
 - Python Version: 3.7.8

**Describe the bug // Steps to reproduce**
The example script under _examples\endpoint_standard\enriched_events_query.py_ contains code that won't work, example CLI:

```
python enriched_events_query.py --apitoken foo/bar --cburl [someurl] --orgkey blah--query ping.exe --fields process_cmdline
```

Yields:

```
Traceback (most recent call last):
  File "enriched_events_query.py", line 80, in <module>
    sys.exit(main())
  File "enriched_events_query.py", line 63, in main
    query.set_fields(args.fields)
AttributeError: 'EnrichedEventQuery' object has no attribute 'set_fields'
```

I discovered this while trying to figure out how to set the fields I want to return for an EnrichedEventQuery.

It seems like there isn't a way to set the fields you want returned at the moment.

Thanks,
Tom

**Comment by avanbrunt-cb** [comment]
@tlansec This bug is occurring because this example script is using unreleased CBC SDK changes from the Develop branch. If you clone the repo and install the CBC SDK from the Develop branch `pip install .` then this will resolve the bug until we release the next version of the CBC SDK soon.
