### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rdkls** [carbonblack/carbon-black-cloud-sdk-python#155]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: MAC
 - Carbon Black Cloud Products: Endpoint Standard
 - Python Version: 3.8.5

**Describe the bug**
Can't get list of sensor kits.

I'm trying to do this in order to eventually auto-update sensors, in order to do which I need to be able to programmatically retrieve the latest sensor kit details.

First the doc on this is pretty sketchy, and I'd love a working example, so my /guess/ is the way to do this is with SensorKitQuery.

My attempt looks like:

`sensors = SensorKitQuery(doc_class=SensorKit, cb=platform_api).add_sensor_kit_type(sensor_type='WINDOWS').expires('2021-04-19T02:10:29+00:00')`

However the API is just returning an empty 500 response. Which to be fair is an "API breaking" issue, but would be great if the SDK had an example, or protected against this by validating args (perhaps I'm missing a parameter or so ...)

**Comment by avanbrunt-cb** [comment]
@rdkls We don't generally use the Query classes directly instead we perform select operations from the CBCloudAPI object. We should update our documentation to give better examples however for the time being we do have some examples in our test code here https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/develop/src/tests/unit/workload/test_sensor_lifecycle.py#L102-L107

**Comment by avanbrunt-cb** [comment]
Closing as not supported at this point in time
