### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 82d28a** [carbonblack/carbon-black-cloud-sdk-python#162]
**I am unable to set argument expiration_seconds to ...ubs.Binary.download_url because it is a property:**
 - OS: Windows
 - Carbon Black Cloud Products:  Enterprise EDR
 - Python Version: 3.8

**Describe the bug**
I am unable to set argument expiration_seconds to ...ubs.Binary.download_url because it is a property
When I pass in any argument I get ...TypeError: 'str' object is not callable

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
file_pull = ubs.Binary(cb, sample_sha256_hash)
file_pull.download_url(expiration_seconds=30)

**Expected behavior**
download url string should be returned available for 30 seconds

**Screenshots**
none available

**Additional context**
no

**Comment by avanbrunt-cb** [comment]
@82d28a We are going to pick up this bug in our next sprint

**Comment by emitreva-cb** [comment]
This issue is fixed with the new release. Check : https://carbon-black-cloud-python-sdk.readthedocs.io/en/latest/unified-binary-store/
