### ISSUE TITLE
[BUG] Vulnerability Assessment API error with last_sync_ts

### ISSUE THREAD

**Issue by Luisferdavila** [carbonblack/carbon-black-cloud-sdk-python#240]
Good afternoon,
I have found  the following problem in the vulnerability assessment API. Using the request to get an asset view with vulnerability summary (POST <cbc-hostname>/vulnerability/assessment/api/v1/orgs/{org_key}/devices/vulnerabilities/summary/_search)  and adding the field "last_sync_ts" as criteria in the request body to filter with datetime, it returns a 500 error with an empty message, without indicating what happens or the reason for the error. Tested with other fields and these have worked successfully, we think that this is an error of either the API or the documentation. Any help with this is greatly appreciated, thanks!

Attached the request body  that was used:

```
{
    "query": "",
    "rows": 20,
    "start": 0,
    "criteria": {
      "last_sync_ts": {
        "value": "2021-09-21T12:43:46.055575Z",
        "operator": "GREATER_THAN"
      }
    },
    "sort": [
    {
     "field": "last_sync_ts",
      "order": "ASC"
    }
    ]
}

```

https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/vulnerability-assessment/#criteria

**Comment by SergioPenagos** [comment]
Hello
I'm currently working with the Vulnerabilities API and have just ran into this issue. Is there any status on the solution yet?

Thanks.

**Comment by NSDrowned** [comment]
Just tested and I'm having the exact same problem. When using `last_sync_ts` as criteria you get a 500 Internal Server error.

**Comment by JoeDDev** [comment]
Hi geeks, good morning. I am working with this API and have a problem with this criteria, `last_sync_ts` , can this problem be corrected or how should I proceed?

Thanks!

**Comment by kebringer-cb** [comment]
Hi, apologies for the delay on closing this out - the issue has been fixed and works correctly.
