### ISSUE TITLE
[BUG] unable to get/set `ignored` property on Reports retrieved from Watchlists that are a classifier

### ISSUE THREAD

**Issue by crahan** [carbonblack/carbon-black-cloud-sdk-python#246]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: macOS 11.6
 - Carbon Black Cloud Products: Enterprise EDR
 - Python Version: 3.8.0

**Describe the bug**

I might be approaching this incorrectly, but it currently does not appear to be possible to use the Python API to retrieve the `ignored` property for Reports retrieved from Watchlists that are a classifier (i.e., feed-linked). The way to retrieve Reports if the watchlist is a classifier (i.e., feed-linked) is by using `watchlist.feed.reports`:

https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/f47c04a3e1aca919a17f4205df164fafe7091b8c/src/cbc_sdk/enterprise_edr/threat_intelligence.py#L424-L430

However, this prevents getting the `ignored` property for the reports as they are coming from the feed the watchlist is linked to and not from the watchlist itself:

https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/f47c04a3e1aca919a17f4205df164fafe7091b8c/src/cbc_sdk/enterprise_edr/threat_intelligence.py#L1232

How can we leverage the Python API to get reports from a watchlist that's a classifier and get/set the `ignored` status for these reports? The UI allows disabling reports for watchlists that are classifiers. You can do the same using the `reports` API endpoint with a report ID that's structured as `feed.id-report.id`.

I'm currently using the following workaround:

```python
cb = CBCloudAPI(profile=PROFILE)
watchlist = [wl for wl in cb.select(Watchlist) if wl.name == WATCHLIST_NAME][0]
reports = watchlist.reports if watchlist.reports else watchlist.feed.reports

for report in reports:
    url = f"/threathunter/watchlistmgr/v3/orgs/{cb.credentials.ORG_KEY}/reports/{watchlist.feed.id}-{report.id}/ignore"
    resp = cb.session.get(url=url)
    ignored = False
    
    if resp.status_code == 200:
        ignored = resp.json().get('ignored', False)
        
    print(report.title)
    print(ignored)
```

However, it would be helpful (and cleaner) if we did not have to fall back on making a direct REST API call and could use the existing `Watchlist` and `Report` objects exposed through the Python API for this purpose as well. 

**Steps to Reproduce**

Steps to reproduce the behavior (Provide a log message if relevant):
1. retrieve reports from a feed-linked watchlist using `watchlist.feed.reports`
2. try retrieving the `.ignored` property for each report in the returned list.
3. An `InvalidObjectError` will be raised stating "ignore status only applies to watchlist reports".

**Expected behavior**

It should be possible to retrieve Reports from a feed-linked watchlist and get/set the `ignored` status for those reports.

**Comment by abowersox-cb** [comment]
Tests have shown that the "feedid-reportid" syntax works for querying or setting the ignore status of a report even if the feed is _not_ currently subscribed to by a watchlist.  The code for `.ignored`, `.ignore()`, and `.unignore()` is being modified to use this syntax if a feed ID is present.

**Comment by abowersox-cb** [comment]
Issue resolved on `develop` branch, will be part of next CBC SDK release.
