### ISSUE TITLE
[Question] Unused dependencies

### ISSUE THREAD

**Issue by sevdog** [carbonblack/carbon-black-cloud-sdk-python#255]
**Describe**

<details>
  <summary>In this package dependencies list there are some unused packages</summary>
https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/0234f0518d215c7c7be13e57eaf7e7f3545e4acc/setup.py#L18-L32

https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/0234f0518d215c7c7be13e57eaf7e7f3545e4acc/requirements.txt#L1-L14
</details>

**Steps to Reproduce**
Use [pipreqs ](https://github.com/bndr/pipreqs)with this command

```shell
pipreqs --mode no-pin --dif requirements.txt 
```

Except requirements for docs/lint/test there are unused elements (ie: pika, python-dateutil)

**Expected behavior**
Do not require on install packages which are not necessary.

**Comment by kebringer-cb** [comment]
Thanks for identifying this. I've created an internal issue CBAPI-3400 to track this in the new year.

**Comment by dganev-cb** [comment]
`python-dateutil` is being used in `src/cbc_sdk/utils.py`, the package that needs to be removed is `pika`.

**Comment by sevdog** [comment]
To be more complete:

`pygments` is listed in install requires but is used only in docs, so it should not be an "install requirement".

`cachetools` is [not used at all](https://github.com/carbonblack/carbon-black-cloud-sdk-python/search?q=cachetools), [like ](https://github.com/carbonblack/carbon-black-cloud-sdk-python/search?q=prompt_toolkit)`prompt_toolkit`.

There is no ".proto" files, so there not seems to be any usage of `protobuf` too.

**Comment by dganev-cb** [comment]
Good calls, I will investigate further!

**Comment by dganev-cb** [comment]
@sevdog I've pushed a PR you can check it out. Again thanks for raising those issues!

**Comment by sevdog** [comment]
@dganev-cb nice job, thank you.
