### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 82d28a** [carbonblack/carbon-black-cloud-sdk-python#271]
**I am seeing this behavior on: (please complete the following information):**
 - OS: Windows 10
 - Carbon Black Cloud Products: Enterprise EDR
 - Python Version: 3.9.6

**Describe the bug**
Attempting to add IOCs to existing report, where the report is part of existing watchlist copies the report with new entry instead of updating existing report. 

I followed the example below in documentation. 

'https://carbon-black-cloud-python-sdk.readthedocs.io/en/latest/watchlists-feeds-reports/?highlight=watchlist#adding-the-report-to-a-watchlist' Follow example of "Alternatively, you can update an existing report, adding more IOCs..."

>>> from cbc_sdk.enterprise_edr import Watchlist, Report, IOC_V2
>>> watchlist = api.select(Watchlist, 'R4cMgFIhRaakgk749MRr6Q')
>>> report_list = [report for report in watchlist.reports if report.id == '47474d40-1f94-4995-b6d9-1d1eea3528b3']
>>> report = report_list[0]
>>> report.append_iocs([IOC_V2.create_query(api, 'evil-connect', 'netconn_ipv4:10.8.16.4')])
>>> report.save_watchlist()

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
1. Create a report A with 1st ioc that is associated with a watch list. 
2. Go to 'https://carbon-black-cloud-python-sdk.readthedocs.io/en/latest/watchlists-feeds-reports/?highlight=watchlist#adding-the-report-to-a-watchlist' and follow example of "Alternatively, you can update an existing report, adding more IOCs..."
3. Run example code to add 2nd ioc to existing report A. 
4. Validate report A is missing 2nd ioc. 
5. Validate addition of cloned report A (report id is different) by searching for 2nd ioc id using https://defense-prod05.conferdeploy.net/enforce/watchlists/add/reports. I see cloned report A (has 1st and 2nd IOCs)

**Expected behavior**
Added IOC's to be added to an existing report in a Watchlist. 

**Screenshots**

**Additional context**

**Comment by abowersox-cb** [comment]
It looks like the example is wrong.  Here is the correct sequence for your example:

```
from cbc_sdk.enterprise_edr import Watchlist, Report, IOC_V2
watchlist = api.select(Watchlist, 'R4cMgFIhRaakgk749MRr6Q')
report_list = [report for report in watchlist.reports if report.id == '47474d40-1f94-4995-b6d9-1d1eea3528b3']
report = report_list[0]
report.append_iocs([IOC_V2.create_query(api, 'evil-connect', 'netconn_ipv4:10.8.16.4')])
report.update()  # <-- this line is changed
```

Please try that and see if this does what you expect.

I expect to be making documentation changes that will do the following:
* Clarify in the description for `save_watchlist()` that it is _not_ to be used for updating reports that are _already part_ of a watchlist.
* Change the example in the guide to reflect what I just mentioned.

**Comment by abowersox-cb** [comment]
@82d28a please validate that the sequence of operations in the above (modified) example works for you. I need this feedback to allow this ticket to proceed.

**Comment by 82d28a** [comment]
Confirmed .update() method works for updating existing reports that are part of a watchlist. Thank you for the clarification.

**Comment by abowersox-cb** [comment]
With pull request #275 merged, this issue can be closed.
