### ISSUE TITLE
[BUG] Replace_rule will fail on Valid operation types (including RUN_INMEMORY_CODE)

### ISSUE THREAD

**Issue by csanders-git** [carbonblack/carbon-black-cloud-sdk-python#280]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: [e.g. iOS]: MacOS 12.3.1
 - Carbon Black Cloud Products: [e.g. Endpoint Standard, Enterprise EDR, Audit & Remediation]: CB CLoud
 - Python Version: [e.g. 3.6]: 3.9.10

**Describe the bug**

Carbon Black implements a Rule Update feature as part of its API.
Rules of type REPUTATION are analogous to the "built in rules" that can be specified in a given policy.
In our examples, we try to update a rule as outlined in the API documentation 
(https://developer.carbonblack.com/reference/carbon-black-cloud/cb-defense/latest/rest-api/#policy)
See section on 'Update Existing Rule'. 

Depending on the content of the JSON, it is possible to receive a notification that malformed JSON has been provided.
This notification (see below), is actually a reference to the fact that an 'Operation Type' is not supported by the Java backend.

HOWEVER, this Operation Type was received initially from the backend and we're simply trying to change the action of the rule.

What this indicates to us, is that when the operation 'RUN_INMEMORY_CODE' code was added, the CB developer neglected to properly updated the supported enum types of 'PolicyOperationType' within the com.scargo.domainmodel.request.support.PolicyOperationType class.
This omission, results in a failure to be able to update rules as outlined within the API.
Please address this issue by fixing your backend code. 

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):

The following example would trigger the issue:

1) Have a policy with the UI field 'Executes code from memory' under the 'suspected malware' section set to 'Action' Deny or Terminate.
2) Use the API or API wrapper to modify that rule. 
3) Observe that the API fails spectacularly

```
(Pdb) print(updated_rule)
{'action': 'DENY', 'application': {'type': 'REPUTATION', 'value': 'SUSPECT_MALWARE'}, 'operation': 'RUN_INMEMORY_CODE', 'required': 'False', 'id': '816'}
(Pdb) policy.replace_rule(id, updated_rule)
*** cbc_sdk.errors.ClientError: Received error code 400 from API: {"error_code":"MALFORMED_JSON","message":"Malformed JSON input: Cannot deserialize value of type `com.scargo.domainmodel.request.support.PolicyOperationType` from String \"RUN_INMEMORY_CODE\": value not one of declared Enum instance names: [MODIFY_SYSTEM_EXE, PASSTHRU, CRED, RANSOM, NETWORK_SERVER, POL_INVOKE_NOT_TRUSTED, IMPERSONATE, MICROPHONE_CAMERA, INVOKE_SYSAPP, NETWORK_CLIENT, BYPASS_REG, BUFFER_OVERFLOW, BYPASS_API, USER_DOC, CODE_INJECTION, BYPASS_NET, KEYBOARD, BYPASS_ALL, RUN, INVOKE_CMD_INTERPRETER, MODIFY_SYTEM_CONFIG, ESCALATE, BYPASS_FILE, RUN_AS_ADMIN, BYPASS_PROCESS, NETWORK, KERNEL_ACCESS, NETWORK_PEER, PACKED, INVOKE_SCRIPT, MEMORY_SCRAPE, BYPASS_SELF_PROTECT, TAMPER_API]\n at [Source: (PushbackInputStream); line: 1, column: 126] (through reference chain: com.scargo.integration.request.PolicyRuleRequest[\"ruleInfo\"]->com.scargo.domainmodel.request.support.PolicyRuleV2[\"operation\"])","field":"ruleInfo.operation"}
```

You can also see in the UI when modifying this field that the operation type is mentioned AND supported via the undocumented https://defense-prod05.conferdeploy.net/appservices/v5/orgs/14947/policies/

```
{
  "application": {
    "type": "REPUTATION",
    "value": "SUSPECT_MALWARE"
  },
  "operation": "RUN_INMEMORY_CODE",
  "action": "DENY"
}
```
**Expected behavior**
Updates the rule as expected

**Comment by kebringer-cb** [comment]
Thanks for reporting this - I'll work with the backend team to resolve it.

**Comment by kebringer-cb** [comment]
Hi, apologies for the delay in the response.  This issue was addressed in the release of the v1 Policy Service which replaced the older implementation.
* Information on the policy service v1 API is here: https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/policy-service/
* The v1 policy service API was added in version 1.4.0 of this python SDK.  Release notes: https://developer.carbonblack.com/2022/07/announcing-the-release-of-v1.4.0-of-carbon-black-cloud-python-sdk/
* Information on changes and how to migrate to the new API are here: https://developer.carbonblack.com/reference/carbon-black-cloud/guides/api-migration/integrationservices-policy-v3-migration/
