### ISSUE TITLE
[Documentation] Not Able to Find An Example for Using `PaginatedQuery` to List Devices with Pagination

### ISSUE THREAD

**Issue by binni-hubble** [carbonblack/carbon-black-cloud-sdk-python#320]
I am trying to list the devices using the SDK function (something like `query = cbc.select(Device).where('1')` ) but I would like to do it with pagination. After going through all the documentation and examples, I am not able to find the good example to know how to use the PaginatedQuery class to get devices or any other entity.

*Questions*
1. How to know what is the total number of items when querying using pagination?
2. How to loop over the PaginatedQuery or items to get all the items?
3. How to know where to stop the loop?

Here is what I am trying 
```
cbc = CBCloudAPI(url='https://xxx.yyy', token='zzz, org_key='aaa', ssl_verify=True)
query = cb.select(Device).where('1')
paginated_query = PaginatedQuery(Device, cb, query).batch_size(5)

print("len paginated : ", len(paginated_query))
print("item : ", paginated_query.getitem(1))

```

Errors
```
Traceback (most recent call last):
  File "src/cbc_harness.py", line 20, in <module>
    print("len paginated : ", len(paginated_query))
  File "/Users/****/python3.8/site-packages/cbc_sdk/base.py", line 1309, in __len__
    return self._count()
AttributeError: 'PaginatedQuery' object has no attribute '_count'

OR

Traceback (most recent call last):
  File "src/cbc_harness.py", line 20, in <module>
    print("len paginated : ", paginated_query.getitem(1))
AttributeError: 'PaginatedQuery' object has no attribute 'getitem'
```

**Comment by abowersox-cb** [comment]
I can tell you for certain that `PaginatedQuery` does not work in the way that you are trying to use it.  It mostly seems to exist as a base class for other queries to use to provide pagination support.  However, `DeviceSearchQuery` (which is the query you're getting when you call `cb.select(Device)`) is not one of those.

We'll have to deal with this in a separate code update, and I am making that note on our internal ticket.

**Comment by abowersox-cb** [comment]
Upon further review, it looks like this code is not correct. `PaginatedQuery` should not be used directly under
any circumstances; it is a base class providing functionality to other query classes.

However, this is not something you need to worry about; most queries will automatically paginate themselves by
submitting multiple requests to the server, to avoid timing out on lengthy responses.

In the case of `Device` queries, you can easily get all the information you want. The total number of items may be
obtained by getting the length of the query:

```
>>> cbc = CBCloudAPI(profile='sample')
>>> query = cbc.select(Device)
>>> len(query)
1339
```

You can loop over a query using the standard `for` loop construct:

```
>>> cbc = CBCloudAPI(profile='sample')
>>> query = cbc.select(Device)
>>> for device in query:
...     do_something_with_device(device)
...
```

And you can exit this loop whenever necessary:

```
>>> cbc = CBCloudAPI(profile='sample')
>>> query = cbc.select(Device)
>>> for device in query:
...     need_to_stop = do_something_with_device(device)
...     if need_to_stop:
...         break
...
```

If you want to deal with only segments of the total query at once, you can use the list slice syntax on the query to
get only that segment of the values:

```
>>> cbc = CBCloudAPI(profile='sample')
>>> query = cbc.select(Device)
>>> k = query[100:200]  # get 100 elements beginning at index 100
>>> len(k)
100
```

Or you can bring the entire list into memory at once:

```
>>> cbc = CBCloudAPI(profile='sample')
>>> query = cbc.select(Device)
>>> devices = list(query)
>>> len(devices)
1339
```

Hopefully this clarifies matters.

**Comment by abowersox-cb** [comment]
Information supplied to customer; closing ticket.
