### ISSUE TITLE
Allow usage of streaming requests to download Devices

### ISSUE THREAD

**Issue by sevdog** [carbonblack/carbon-black-cloud-sdk-python#329]
As of now the `download` method for Device model uses: [`get_raw_data`](https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/706a4f9ed5267c35b310e4a8318233212f1e0b98/src/cbc_sdk/connection.py#L490) method has two pitfalls:

- it calls a method which tries to turn results into JSON and relies that this parsing fails (which is just a waste of time/resources and also may lead to errors)
- it does not allow using streaming (see [requests doc](https://docs.python-requests.org/en/latest/user/advanced/#streaming-requests)) for large responses, which slows down the processing (ie: when downloading CSV for about 10k devices)

It would be nice to be able to use the streaming API of requests, however to use this correctly the JSON parsing should be removed from this method or it would waste any benefit from streaming (since JSON parsing requires the whole response available).

Thus the download method should have an optional parameter to use the `api_request_iterate` method instead of `get_raw_data`.

**Comment by avanbrunt-cb** [comment]
@sevdog Thanks for the request we will consider this with our future work around the device API

**Comment by sevdog** [comment]
> with our future work around the device API
Hi @avanbrunt-cb, what do you mean with "work around"? Are you going to refactor those APIs in a next release?

**Comment by avanbrunt-cb** [comment]
@sevdog sorry did not mean to imply a workaround. We have plans to make a better API on the backend which will improve the capabilities for API users. That work has not finished so I am unsure what release that will be available. I will follow up when the CBC SDK work has started to improve this area of the SDK

**Comment by avanbrunt-cb** [comment]
This has been replaced by `def export()` on the `DeviceSearchQuery` class

https://carbon-black-cloud-python-sdk.readthedocs.io/en/latest/cbc_sdk.platform/#cbc_sdk.platform.devices.DeviceSearchQuery.export
