### ISSUE TITLE
Link validators in Report and IOC_V2 

### ISSUE THREAD

**Issue by lucaCigarini** [carbonblack/carbon-black-cloud-sdk-python#356]
Hello team!

I'm using Carbon Black Cloud Python SDK to download, edit and upload Feed Reports and I've stumbled upon a few weird behaviours:

1. Reports have a link field that can be set to provide more informations regarding the specific report. I have noticed that a URL with the schema (e.g. https) won't be [validated](https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/develop/src/cbc_sdk/enterprise_edr/threat_intelligence.py#L1184) by the SDK. What are the reasons behind this choice?
2. IOC_V2 have a link field just like reports. Nevertheless if I try to provide a URL, without schema but with a path, this triggers a [validation error](https://github.com/carbonblack/carbon-black-cloud-sdk-python/blob/develop/src/cbc_sdk/enterprise_edr/threat_intelligence.py#L1728). So a link that was ok for reports won't work for iocs. Furthermore, sometimes iocs are downloaded from Carbon Black Cloud Servers with an invalid link (a simple string or a URL with schema and path) causing a Validation Error when trying to reupload the IOC. Is this a bug?

**Comment by avanbrunt-cb** [comment]
@lucaCigarini Thanks for reporting this item we will create a bug ticket and get this addressed

**Comment by abowersox-cb** [comment]
PR #365 fixes this by changing validation to accept either IPv4 addresses, domain names, or URIs. This is done for both report and IOC link fields.
