### ISSUE TITLE
Feature request: add asset-group search to devices

### ISSUE THREAD

**Issue by sevdog** [carbonblack/carbon-black-cloud-sdk-python#456]
From 27th November 2023 a new feature was addes to CB cloud: [asset groups](
https://docs.vmware.com/en/VMware-Carbon-Black-Cloud/services/rn/vmware-carbon-black-cloud-console-release-notes/index.html#Update%20-%2027%20November%202023-Asset%20Groups).

It would be nice if the python client allows selecting devices by providing this information (the group name or ID).

**Comment by avanbrunt-cb** [comment]
This is already supported today using `add_criteria` function on the query. See https://carbon-black-cloud-python-sdk.readthedocs.io/en/latest/cbc_sdk.platform/#cbc_sdk.platform.devices.DeviceSearchQuery.add_criteria

**Comment by avanbrunt-cb** [comment]
Further Asset Group support will be added in 1.5.1
