### ISSUE TITLE
Feature request: add new device export API

### ISSUE THREAD

**Issue by sevdog** [carbonblack/carbon-black-cloud-sdk-python#457]
From [documentation](https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/devices-api/#export-devices) the current device "download" API is deprecated in favor of the new "export" API.

It would be nice if this was integrated in the python client, since it has a significant changes because the download API directly respondes with the exported data, while the export API responds with the URL of the export job which should be polled to check completition and then it should be downloaded from an other URL.

**Comment by avanbrunt-cb** [comment]
Supported added with https://github.com/carbonblack/carbon-black-cloud-sdk-python/pull/479 and will be released in 1.5.1
