### ISSUE TITLE
[BUG][Feature request] Add details to affected_assets

### ISSUE THREAD

**Issue by mik0w** [carbonblack/carbon-black-cloud-sdk-python#512]
**I am seeing this behaviour on: (please complete the following information):**
 - Carbon Black Cloud Products: CBC Python SDK

**Describe the bug**
It's more an improvement than a bug, but I believe it would make the SDK more useful. Basically it seems to be impossible to clearly identify the device using Vulnerabilities model (e.g. using this filter: `api.select(Vulnerability).set_severity("CRITICAL", "EQUALS")`).
The response from the SDK is a list of Vulnerability objects, each of which containing list of affected assets (but unfortunately only the names of the assets): 

```
 affected_assets: [list:2 items]:
                     [0]: test_asset_1
                     [1]: test_asset_2
```

However, to unambiguously identify each asset, it would be beneficial if the Vulnerability model provided additional parameters for each asset, such as the asset ID and MAC address, as sometimes the names of devices can repeat across the organization (due to either people naming their machines with the company's name, or due to DHCP server setting up names etc.): 

```
 affected_assets: [list:2 items]:
                     [0]: MacBook.local
                     [1]: MacBook.local
```

In the situation above, it's very difficult to process the information further, especially if one's going to e.g. contact specific individuals so they update their software. I am forced to use plain API requests (this way I am able to filter for vulnerable devices, using this endpoint: 
`vulnerability/assessment/api/v1/orgs/{org_id}/vulnerabilities/{cve_id]/devices`, even though I'd prefer to use SDK. 

**Expected behavior**
Vulnerability object contains enough information to unambiguously determine the vulnerable assets (not only hostname, but also MAC address or ID).

**Comment by avanbrunt-cb** [comment]
@mik0w This is a limitation with the API on the backend as the Vulnerability search API only returns the name. We've requested before but it is not a high priority for them to implement.

That being said we do have the following function implemented in the Vulnerability object to fetch the affect devices

`get_affected_assets` - https://carbon-black-cloud-python-sdk.readthedocs.io/en/latest/cbc_sdk.platform/#cbc_sdk.platform.vulnerability_assessment.Vulnerability.get_affected_assets
