### ISSUE TITLE
[BUG] Do not install backports._datetime_fromisoformat on recent python distributions

### ISSUE THREAD

**Issue by prose-leviathan** [carbonblack/carbon-black-cloud-sdk-python#520]
**I am seeing this behaviour on: (please complete the following information):**

- Windows 10 64 Bit 
- Python 3.12

**Describe the bug**
There seems to be dependency on backports._datetime_fromisoformat . As I gather from https://github.com/movermeyer/backports.datetime_fromisoformat , it is a backport of a datetime feature present from Python 3.11 to older versions. It unfortunately prevents me from using the SDK on my machine, as it requires a C++ compiler installed , and I can't install it due to to security reason. I am able to use the latest Python versions however, so this requirement seems obsolete and could be made more optional.

**Steps to Reproduce**
Install with pip in a windows device without a C++ compiler installed

**Expected behavior**
Make the dependency optional for newer Python installation

**Screenshots**
![image](https://github.com/carbonblack/carbon-black-cloud-sdk-python/assets/97615419/df5bd564-47f6-487e-8dd8-6d1d73c64eeb)

**Additional context**
I am in Enterprise setting where there is no workaround possible. I also think some SOAR environment may not be able to install the sdk due to this (especially those where the build environment is not clear, and the engineers can only point to specific pip packages)

**Comment by prose-leviathan** [comment]
I have opened #521 with a proposal to implement conditionality based on the python version

**Comment by avanbrunt-cb** [comment]
Thank for the proposal we will look into it

**Comment by avanbrunt-cb** [comment]
Created a new PR with some minor changes to run our CI/CD against the branch: https://github.com/carbonblack/carbon-black-cloud-sdk-python/pull/523

**Comment by avanbrunt-cb** [comment]
Merged and will be released in the next version soon

**Comment by avanbrunt-cb** [comment]
Fixed in 1.5.4
