### ISSUE TITLE
[BUG] accessing process.process_sha256 results in a query

### ISSUE THREAD

**Issue by oleksii-threatray** [carbonblack/carbon-black-cloud-sdk-python#544]
**I am seeing this behaviour on:**
 - OS: ubuntu
 - Carbon Black Cloud Products: Enterprise EDR
 - Python Version: 3.11
 - Python CBC SDK version: 1.5.6 (latest)

**Describe the bug**
After getting  processes from CBC with the query: 
`query = cbc_api.select(Process).where(filter_query).set_fields(['process_guid', 'process_sha256', 'backend_timestamp'])`
accessing `process.process_sha256` value of any process results in an additional query, which significantly degrades the performance at scale.
At the same time accessing this value through `process._info['process_sha256']` returns the value without queries.
Note that accessing other fields - `process_guid` or `backend_timestamp` - returns the value without queries, as expected.

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
1. Query `Process` from CBC with `set_fields(['process_sha256'])`:
`query = cbc_api.select(Process).where(filter_query).set_fields(['process_guid', 'process_sha256', 'backend_timestamp'])`
2. Get any process:
`first_process = list(query)[0]`
3. Access the `process_sha256`:
`print(first_process.process_sha256)`
4. Observe an additional query

**Expected behavior**
`process.process_sha256` returning the value immediately, since the value is already in the object under the `self._info["process_sha256"]` key.

**Additional context**
I've took a look at the `process_sha256` property implementation in the `processes.py` in the sdk and somethings seems off to me:
```
    def process_sha256(self):
        """Returns a string representation of the SHA256 hash for this process."""
        if "process_hash" in self._info:
            return next((hsh for hsh in self.process_hash if len(hsh) == 64), None)
        elif "process_hash" in self.summary._info["process"]:
            return next((hash for hash in self.summary._info["process"]["process_hash"] if len(hash) == 64), None)
        else:
            return None
```
Here `self.summary._info["process"]["process_hash"]` is accessed while in reality I see the `sha256` value in the object under the `self._info["process_sha256"]` key.

**Comment by avanbrunt-cb** [comment]
Fixed in 1.5.7
